import random
import requests

# URL for USD based currency
url = 'https://v6.exchangerate-api.com/v6/411f4ce8de9fa66bc0529059/latest/USD'

# Making request and convert to json
response = requests.get(url)
data = response.json()

# JSON object of ILS currency
currency = data["conversion_rates"]["ILS"]

# Declare variables that will be generated by global scope in the next methods
interval_min = 0
interval_max = 0
guess_number = 0
win = False

def get_money_interval(ils_currency, difficulty, total_money_in_usd):
    global interval_min, interval_max
    interval_min = ils_currency * total_money_in_usd - (5 - difficulty)
    interval_max = ils_currency * total_money_in_usd + (5 - difficulty)
    interval_min = float(f"{interval_min:.2f}")
    interval_max = float(f"{interval_max:.2f}")
    return interval_min, interval_max

def get_guess_from_user(usd_amount):
    global guess_number
    guess_number = input(f"Please enter your guess ILS currency for {usd_amount}$: ")
    guess_number = float(guess_number)

    # User guess number validation
    while not guess_number > 0:
        try:
            guess_number = float(guess_number)
            if guess_number < 0:
                raise ValueError
        except ValueError:
            print("You didn't entered a number bigger than 0!")
            guess_number = input(f"Please enter your guess ILS currency for {usd_amount}$: ")
    return float(guess_number)

def play(difficulty):
    global interval_min, interval_max, currency, win
    random_usd = random.randint(1, 100)
    user_guess = get_guess_from_user(random_usd)
    interval_min, interval_max = get_money_interval(currency, difficulty, random_usd)
#     print(f"""Interval_Min: {interval_min}, Your_Guess: {user_guess}, Interval_Max: {interval_max},
# Total_to_guess: {random_usd * currency}""")
    if interval_min <= user_guess <= interval_max:
        print("True\nCongratulations! you won the Currency Roulette Game!")
        win = True
    else:
        print("False\nUnfortunately you lost the memory game, feel free to try another time :)")
