version: '3'
services:
    web:
        build: .
        image: dordiamant47/flaskproject:latest
        ports:
          - "8777:8777"
        environment:
              FLASK_APP: MainScores.py
              FLASK_RUN_HOST: 0.0.0.0
