import random

# Declare variables that will be generated by global scope in the next methods
secret_number = 0
guess_number = 0
win = False

def generate_number(difficulty):
    global secret_number
    secret_number = random.randint(1, difficulty)
    return secret_number


def get_guess_from_user(difficulty):
    global guess_number
    valid_range = range(1, difficulty + 1)
    guess_number = input(f"Please enter your guess from 1 to {difficulty}: ")

    # User guess number validation
    while guess_number not in valid_range:
        try:
            guess_number = int(guess_number)
            if guess_number not in valid_range:
                raise ValueError
        except ValueError:
            print("You didn't entered a number in the range!")
            guess_number = input(f"Please enter your guess from 1 to {difficulty}: ")
    return guess_number


def compare_results(guess, generated_random):
    if guess == generated_random:
        return True
    else:
        return False


def play(game_difficulty):
    global win
    random_number = generate_number(game_difficulty)
    guess = get_guess_from_user(game_difficulty)
    result = compare_results(random_number, guess)
    if result:
        print("True\nCongratulations! you won the guess game!")
        win = True
    else:
        print("False\nUnfortunately you lost the guess game, feel free to try another time :)")
    # print(f"Random number is {random_number}")
